@url=http://localhost
@registerPort=5501
@paymentPort=5502

### Test registration service
POST {{url}}:{{registerPort}}/register
Content-Type: application/json

{
    "name": "Stu Dent",
    "email": "stu@dent.com",
    "class": "digital media",
    "cost": 500
}

### Test payment services
POST {{url}}:{{paymentPort}}/pay
Content-Type: application/json

{
    "email": "stu@dent.com",
    "cost": 500
}